version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/data"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-dependencies:
        patterns:
          - "*"