name: cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Aggregation
        uses: ./.github/workflows/aggregation.yml
      - name: Deplyoment
        uses: ./.github/workflows/deployment.yml