name: cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  data-aggregation:
    name: data-aggregation
    uses: ./.github/workflows/aggregation.yml

  deployment:
    name: deployment
    uses: ./.github/workflows/deployment.yml
    