name: test

on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest
        run: npm run test:unit
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright
        run: npm run test:e2e

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: ./data/requirements.txt
      - name: Install dependencies
        run: pip install -r ./data/requirements.txt
      - name: Run pytest
        run: PYTHONPATH=./data pytest tests/backend/
